### ISSUE TITLE
Countdown not working

### ISSUE THREAD

**Issue by Superjd10** [jswetzen/ppstagedisplay#14]
Before posting this, I have been trying to figure out how to make it work but there are no comments to understand really the code (and I am not good with javascript, so the whole code is confusing to me). I tried to "parse" the countdown like this:

```
function parseCountdown(data) {
  if(data == "--:--:--" || data.indexOf(' ') >= 0) {
    data = "";
  }
  return data;
}
```

(I used console.log(data); in contentPreprocessors to get the data)

Right now the code just count backwards from 0:00:00 to -0:00:07 or so in a 1:00:00 countdown and then restarts. console.log(data) shows the real "content" of the data (0:59:59 then line break with --:--:-- and then 0:59:58 then line break with --:--:-- and so on, that's the why of the if in the function)

Can you comment a bit more the code or help me resolve this?

Also, I gave up in this point but the clock (in Pro6 Mac Stage Display) is displayed like 2016/11/19 11:57:42 p.m. but in the app, for some reason I have not figured out yet, only the hour is displayed in 24 hour format (I tried checking the functions in scripts.js but these were confusing so better not touch it for now)

Thanks for the help and this great tool!

**Comment by jswetzen** [comment]
Could you log the output of parseTime(data) instead of data, then we can verify that the function works correctly. It's supposed to output 24 hour format (that's one of the things parseTime does) to be consistent on Mac and Windows versions of ProPresenter, and it's what we most commonly use here in Sweden.

But to the real problem: if we can rule out an error in parseTime, then it's on the client side.
On line 31 in public/script.js, after `var seconds = getSeconds(content);`,  add `console.log("timer " + key + ": " + seconds);`, to see  what the time is parsed to. Another log after line 55 would be good too: `console.log("content: " + content);`, to see the final content.

**Comment by kevindoveton** [comment]
@jswetzen i'm not able to replicate this, @Superjd10 what version of propresenter are you using on what operating system?

**Comment by jswetzen** [comment]
@Superjd10 mentioned "Pro6 Mac", is that correct? What specific ProPresenter 6 version?

I'm wondering now if ProPresenter is really sending "p.m.", instead of "pm" like parseTime expects it. I could add that to the tests and see if  it works.

**Comment by kevindoveton** [comment]
@jswetzen i've just replicated this in pro6, I think the problem is server side, not client side but haven't had time to explore it. Client side its returning the count down as zero every second or third cycle.

**Comment by jswetzen** [comment]
I added testing with Travis CI, so now when this problem is fixed, we can add a test so that it doesn't happen again. Of course it's possible to test locally with `npm test`, but now it's automatic too.

**Comment by kevindoveton** [comment]
The issue is that pro6 doesn't pad out the hours in its countdown - it returns 0:10:23 instead of 00:10:23 as pro5 would, so it wasn't being detected as a countdown. I've updated the match regexp to fix it.
